version: '3.1'

services:
    mediapedia-api:
        image: mediapedia-api:local
        restart: always
        environment:
            POSTGRES_SERVER: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: docker
            POSTGRES_PASS: example
            POSTGRES_DB: mediapedia
        depends_on: 
            - postgres
        links:
            - postgres:postgres
        ports:
          - 80:1323
    postgres:
        image: postgres:12.1
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: docker
            POSTGRES_DB: mediapedia
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql