version: '3.1'

services:
    mediapedia-api:
        image: mediapedia-api:local
        restart: always
        environment:
            MONGO_SERVER_URL: mongo
            MONGO_USER: root
            MONGO_PASS: example
        depends_on: 
            - mongo
        links:
            - mongo:mongo
        ports:
          - 80:1323
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
